"""initial revision

Revision ID: 0c451ef318cc
Revises: 
Create Date: 2026-05-29 14:11:11.914188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c451ef318cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('local_index', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.CheckConstraint("task_type IN ('ASLEEP', 'ASYNC HTTP REQUEST', 'CELERY TASK PROCESSING', 'COROUTINE LOG')", name='tasks_type_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tasks_users_id_foreign'),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('user_id', 'local_index', name='tasks_user_id_local_index_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
