"""fixes

Revision ID: d02552336913
Revises: 0dff999ffd0e
Create Date: 2026-06-17 14:30:28.805221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02552336913'
down_revision: Union[str, Sequence[str], None] = '0dff999ffd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Text(), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('tasks_user_id_local_index_unique'), 'tasks', type_='unique')
    op.drop_column('tasks', 'local_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('local_index', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tasks_user_id_local_index_unique'), 'tasks', ['user_id', 'local_index'], postgresql_nulls_not_distinct=False)
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
