"""users_OTP

Revision ID: d8acfe04e0bd
Revises: e915b8341670
Create Date: 2026-06-08 14:38:41.524982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8acfe04e0bd'
down_revision: Union[str, Sequence[str], None] = 'e915b8341670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('otp_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_created_at')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
